{
    'name': 'Hotel Indah Lestari',
    'version': '14.0.1.0.0',
    'category': 'Services',
    'summary': 'Module for managing the Hotel',
    'sequence': '10',
    'author': 'Arga Dwi Ardinata',
    'maintainer': 'Arga Dwi Ardinata',
    'website': 'tes.com',
    'depends': [
        "mail",
    ],
    'demo': [],
    'data': [
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/order_hotel.xml',
        'views/ordered.xml',
        'views/canceled.xml',
        'views/not_confirm.xml',
        'views/custommers.xml',
        'views/rooms.xml',
        'views/confirmation.xml',
        'report/invoicereport.xml',
        'report/report.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}